version: "3"
services:
  web:
    build: .
    ports:
      - 80:80
    volumes:
      - ./app:/var/www/html/
    environment:
      PHP_ERROR_REPORTING: E_ALL
    links:
      - mysql
      - redis
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
  redis:
    image: redis:latest
    ports:
      - 6379:6379
